name: vit_tiny_patch16_224
model_name: vit_pretrained_cifar100
pretrained: true
feature_dim: 192
freeze_backbone: true
type: vision_transformer_classification
location: /content/drive/MyDrive/MS_Project/Notebooks/models/vit_pretrained_cifar100/checkpoints
model_filename: vit_final_checkpoint.pth
num_classes: 80 # 80% of 100 classes are used for OOD purposes.
patch_size: 4
dropout_rate: 0.1
image_size: 224

# vit_small_patch16_224
checkpoint_keys:
  class_info: class_info
  pretrain_classes: pretrain_classes
  pretrain_examples: pretrain_examples
  model_state_dict: model_state_dict