# Hydra base configuration file

defaults:
  - _self_
  - model: model
  - data: tiny_imagenet # options: cifar100, tiny_imagenet
  - ood: ood
  - cl: continual_learning
  - logging: wandb # options: wandb, tensorboard, none

# General
seed: 42 # random seed for reproducability
device: cuda # CHANGE TO "gpu" IF YOU HAVE ONE
output_dir: /home/alex/repos/ms_project/results/ # Change this to your own path
ind_class_ratio: 0.8 # 80% of classes used for IND training data
ind_example_ratio: 0.75 # 75% of examples used for IND training data
# save_model: false # save the model after training

experiment:
  name: ${model.name}_${data.name}